### ISSUE TITLE
Provide options for provisioning the default user through the service broker

### ISSUE THREAD

**Issue by ajcaldera1** [YugaByte/cf-yugabyte-service-broker#22]
Need to have the service broker provide some kind of option to grant a certain level of permissions to the user that gets created.  With RBAC now enabled, the default user that gets created by the Service Broker has no permissions and a manual step must be executed as the cassandra admin user to grant permissions after the service key has been created.

**Comment by miggy9001** [comment]
With this it would also be nice if they created users defaulted to having read access to the table system.seeds as a minimum because otherwise they can reject connecting because it can not find/validate seeds.

**Comment by ajcaldera1** [comment]
A better approach would be to have the users provisioned with a level of default permissions to be able to access tables, create keyspaces, but not create other roles or make other system modifications. All the users should be provisioned via the service broker so that they can be maintained / audited by other processes. We should allow the user to pass tags via the service broker to provision additional permissions as appropriate.

**Comment by miggy9001** [comment]
@ajcaldera1 read access to all tables by default seems tricky depending on the RBAC use case. I think create keyspace and read access to system tables seems good ground where the user can create a keyspace and tables in that keyspace.

**Comment by aegershman** [comment]
Going to piggy-back off this. Looking for feedback / corrections / concerns / etc.:

I agree, the permissions of the provisioned credentials needs to be *useful*. The credentials that are created, whether they're application-to-service bindings or service keys, should allow for admin access (default to admin? @xyloman @gm2552 @dashaun) by the broker.

A CF user with `developer` scope already has permission to both create and destroy the _entire_ service instance, so if we're going to trust them with that level of responsibility it stands to reason that we can trust them with a greater level of permissions than "none" 😄

Provisioning credentials with zero permissions is actually harmful because it discourages disposable credential sets:

- it requires an admin to assign permissions to the new user, which introduces more tickets & is generally time-inefficient.
- due to the overhead of requesting admins provision their user permissions, it encourages teams to store a single-set of credentials and to share credentials with permissions given to them rather than making new ones

Examples:

- [The mysql broker](https://docs.pivotal.io/p-mysql/2-5/customize-access.html) provisions credentials with admin permissions, but allows service keys to be created in `read_only`
- [The RMQ broker](https://docs.pivotal.io/rabbitmq-cf/1-15/install-config.html#admin-service-key) gives app service bindings full permissions, and let's developers create service instance keys with full admin priviledges
- [The Redis broker](https://docs.pivotal.io/redis/2-0/using.html#call) gives out permissive application-to-service binding credentials && allows full admin keys to be provisioned via service key.
